#ifndef MAX_7221_H
#define MAX_7221_H

// CONTROL REGISTERS FOR MAX7221

#define SHUT_DOWN_REG 0x0C
#define DECODE_MODE_REG 0x09
#define INTENSITY_MODE_REG 0x0A
#define SCAN_LIMIT_REG 0x0B
#define DISPLAY_TEST_REG  0x0F


// VALUES FOR EACH CONTROL REGISTER

#define SHUT_DOWN_VALUE 		0x01
#define DECODE_MODE_VALUE 		0x0F
#define INTENSITY_MODE_VALUE 	0x0F
#define SCAN_LIMIT_VALUE		0x03
#define DISPLAY_TEST_VALUE  	0x00

// DIGIT ADDRESS 

#define DIGIT_ZERO_REG	0x01
#define DIGIT_ONE_REG	0x02
#define DIGIT_TWO_REG	0x03

#endif